#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro setup action node"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  setup::node
}

run() {
  core $@
}

run $@
